services:
  ros:
    build: .
    network_mode: host
    extra_hosts: 
      - "QTRD000339.local:192.168.1.191"
      - "QTRD000353.local:192.168.1.192"
      - "QTRD000375.local:192.168.1.193"
    volumes:
      - /home/robo/bash_aliases:/root/.bash_aliases
      - code:/root/catkin_ws/src/QTrobot_dev
    command: tail -f /dev/null
volumes:
  code: